/**
 * TDC Communications Rate Cards
 * Source: TDC_All_Customer_Master_Price_Sheets_6-24-26.xlsx
 * Updated: 06/26/2026
 */

const RATE_CARDS = {

  UNITI_GA: {
    'UNGA01': { desc: 'Directional Bore Less than 100', rate: 1500, unit: 'EA' },
    'UNGA02': { desc: 'Directional Bore 0-200', rate: 11.5, unit: 'LF' },
    'UNGA03': { desc: 'Directional Bore 201-500', rate: 9, unit: 'LF' },
    'UNGA04': { desc: 'Directional Bore 501+', rate: 9, unit: 'LF' },
    'UNGA05': { desc: 'Directional Bore Place 3x1.25" 0-200', rate: 12.5, unit: 'LF' },
    'UNGA06': { desc: 'Directional Bore Place 3x1.25" 201-500', rate: 10, unit: 'LF' },
    'UNGA07': { desc: 'Directional Bore Place 3x1.25" 501+', rate: 9.5, unit: 'LF' },
    'UNGA08': { desc: 'Directional Bore CBD/High Impact', rate: 15, unit: 'LF' },
    'UNGA09': { desc: 'Directional Bore Place 1x4" Railroad Bore', rate: 14, unit: 'LF' },
    'UNGA10': { desc: 'Traffic Control', rate: 500, unit: 'EA' },
    'UNGA11': { desc: 'Trench Manual Place 2x1.25"', rate: 15, unit: 'LF' },
    'UNGA12': { desc: 'Machine Trench Place 2x1.25"', rate: 12, unit: 'LF' },
    'UNGA13': { desc: 'Place HH', rate: 400, unit: 'EA' },
    'UNGA14': { desc: 'Prep HH', rate: 200, unit: 'EA' },
    'UNGA15': { desc: 'Remove & Replace HH Standard', rate: 550, unit: 'EA' },
    'UNGA16': { desc: 'Remove & Replace HH Double Lid', rate: 650, unit: 'EA' },
    'UNGA17': { desc: 'Remove HH', rate: 200, unit: 'EA' },
    'UNGA18': { desc: 'Access Existing Conduit Standard', rate: 300, unit: 'EA' },
    'UNGA19': { desc: 'Access Existing Conduit 5\'+', rate: 450, unit: 'EA' },
    'UNGA20': { desc: 'Install Marker Post', rate: 15, unit: 'EA' },
    'UNGA21': { desc: 'C&R Concrete', rate: 18, unit: 'SF' },
    'UNGA22': { desc: 'C&R Asphalt', rate: 18, unit: 'SF' },
    'UNGA23': { desc: 'Place SOD', rate: 2.5, unit: 'SF' },
    'UNGA24': { desc: 'Pull Fiber', rate: 1, unit: 'LF' },
    'UNGA25': { desc: 'Decom Fiber', rate: 1, unit: 'LF' },
    'UNGA26': { desc: 'Install Locate Wire', rate: 0.25, unit: 'LF' },
    'UNGA27': { desc: 'Remove Locate Wire', rate: 0.15, unit: 'LF' },
    'UNGA28': { desc: 'Rod & Rope', rate: 0.95, unit: 'LF' },
    'UNGA29': { desc: 'Lash-New', rate: 2.5, unit: 'LF' },
    'UNGA30': { desc: 'Over-Lash', rate: 1.5, unit: 'LF' },
    'UNGA31': { desc: 'Make-Ready', rate: 75, unit: 'EA' },
    'UNGA32': { desc: 'Band Concrete Pole', rate: 100, unit: 'EA' },
    'UNGA33': { desc: 'Place Extension Arm', rate: 90, unit: 'EA' },
    'UNGA34': { desc: 'De-Lash/Re-Lash', rate: 1.5, unit: 'LF' },
    'UNGA35': { desc: 'Install U-Guard', rate: 25, unit: 'EA' },
    'UNGA36': { desc: 'Relocate Fiber Slack', rate: 300, unit: 'EA' },
    'UNGA37': { desc: 'Strand & Cable Removal', rate: 2, unit: 'LF' },
    'UNGA38': { desc: 'Aerial Building Attachment', rate: 250, unit: 'EA' },
    'UNGA39': { desc: 'Utility Pole Placement', rate: 500, unit: 'EA' },
    'UNGA40': { desc: 'Install Weatherhead', rate: 200, unit: 'EA' },
    'UNGA41': { desc: 'Intercept Existing Conduit (Empty Duct)', rate: 200, unit: 'EA' },
    'UNGA42': { desc: 'Intercept Existing Conduit (Occupied Duct)', rate: 300, unit: 'EA' },
    'UNGA43': { desc: 'Core Bore', rate: 250, unit: 'EA' },
    'UNGA65': { desc: 'Emergency Mobilization Fee', rate: 500, unit: 'EA' },
    'UNGA67': { desc: 'Pole Transfer (Standard)', rate: 60, unit: 'EA' },
    'UNGA68': { desc: 'Pole Transfer (Complex)', rate: 120, unit: 'EA' },
    'UNGA77': { desc: 'Hand Trench less than 50\'', rate: 18, unit: 'LF' },
    'UNGA78': { desc: 'Hourly rate for audits and troubleshooting', rate: 100, unit: 'HRS' },
    'UNGA80': { desc: 'Hourly Underground Crew', rate: 175, unit: 'HRS' },
    'UNGA81': { desc: 'Hourly Supervisor', rate: 85, unit: 'HRS' },
    'UNGA82': { desc: 'Mobilization Fee (When Released 1 Job 2.5+ Hours Away)', rate: 200, unit: 'EA' },
    'UNGA84': { desc: 'Set up fee for jobs less than 2000\'', rate: 500, unit: 'EA' },
    'UNGA85': { desc: 'Set up fee for jobs less than 500\'', rate: 1250, unit: 'EA' },
    'UNGA87': { desc: 'Soft Rock Adder', rate: 25, unit: 'LF' },
    'UNGA88': { desc: 'Hard Rock Adder', rate: 40, unit: 'LF' },
    'UNGA89': { desc: 'Decom and Remove Cabinet - Standard - H Frame Only', rate: 1500, unit: 'EA' },
    'UNGA90': { desc: 'Decom and Remove Cabinet - Double Stacked - H Frame Only', rate: 3000, unit: 'EA' },
  },

  UNITI_SC: {
    'UNSC01': { desc: 'Directional Bore 0-200', rate: 11.5, unit: 'LF' },
    'UNSC02': { desc: 'Directional Bore 201-500', rate: 10, unit: 'LF' },
    'UNSC03': { desc: 'Directional Bore 501+', rate: 9, unit: 'LF' },
    'UNSC09': { desc: 'Traffic Control', rate: 500, unit: 'EA' },
    'UNSC10': { desc: 'Trench Manual', rate: 7, unit: 'LF' },
    'UNSC12': { desc: 'Place HH', rate: 400, unit: 'EA' },
    'UNSC20': { desc: 'C&R Concrete', rate: 20, unit: 'SF' },
    'UNSC21': { desc: 'C&R Asphalt', rate: 25, unit: 'SF' },
    'UNSC23': { desc: 'Pull Fiber', rate: 1, unit: 'LF' },
    'UNSC27': { desc: 'Set up fee for jobs less than 2000\'', rate: 500, unit: 'EA' },
    'UNSC28': { desc: 'Set up fee for jobs less than 500\'', rate: 1250, unit: 'EA' },
    'UNSC66': { desc: 'Mobilization > 50 miles', rate: 350, unit: 'EA' },
    'UNSC69': { desc: 'Emergency Mobilization Fee', rate: 500, unit: 'EA' },
  },

  UNITI_SPLICING: {
    'UNSP01': { desc: 'UNSP01-Fusion Splice Cost Per Fiber, 1-24', rate: 24, unit: 'EA' },
    'UNSP02': { desc: 'UNSP02-Fusion Splice Cost Per Fiber, 25-96', rate: 21, unit: 'EA' },
    'UNSP03': { desc: 'UNSP03-Fusion Splice Cost per Fiber, > 96', rate: 16.5, unit: 'EA' },
    'UNSP04': { desc: 'UNSP04-Ribbon Splice Cost Per Ribbon, 1-96', rate: 14.5, unit: 'EA' },
    'UNSP05': { desc: 'UNSP05-Ribbon Splice Cost per Ribbon, > 96', rate: 12, unit: 'EA' },
    'UNSP06': { desc: 'UNSP06-Prep cables into new closure', rate: 200, unit: 'EA' },
    'UNSP07': { desc: 'UNSP07-Re-entry (Enclosure)', rate: 150, unit: 'EA' },
    'UNSP08': { desc: 'UNSP08-Re-entry Aerial (Enclosure)', rate: 165, unit: 'EA' },
    'UNSP09': { desc: 'UNSP09-Mid-Sheath (Includes Enclosure Prep)', rate: 250, unit: 'EA' },HL_GA: {
    'HL-UG02':  { desc: 'Composite UG Conduit Placement - up to 2" conduit', rate: 9, unit: 'LF' },
    'HL-UG18':  { desc: 'Bore, pull additional conduit adder up to 2", Min 36" cover', rate: 1, unit: 'LF' },
    'HL-UG26':  { desc: 'Bore, Soft rock adder (with written approval), Min 36"', rate: 12, unit: 'LF' },
    'HL-UG30':  { desc: 'Bore, Solid rock adder (with written approval), Min 36"', rate: 35, unit: 'LF' },
    'HL-UG34':  { desc: 'Plow, Min 36" Depth, one Duct, includes 2 pre-rips', rate: 3.75, unit: 'LF' },
    'HL-UG40':  { desc: 'Plow, Min 36" Depth, 2nd Duct Adder', rate: 1, unit: 'LF' },
    'HL-UG62':  { desc: 'Joint Trench, Place up to two 2" ducts, Min 36"', rate: 1.5, unit: 'LF' },
    'HL-UG70':  { desc: 'Hand dig trench up to 50\', up to 24"', rate: 16, unit: 'each' },
    'HL-UG72':  { desc: 'Duct rod/locate/rope existing duct', rate: 0.8, unit: 'LF' },
    'HL-UG74':  { desc: 'Place cable in conduit, up to 288 fiber (blow or pull)', rate: 0.95, unit: 'SF' },
    'HL-UG82':  { desc: 'Install Vault, 24x36x24 concrete', rate: 225, unit: 'each' },
    'HL-UG84':  { desc: 'Install Vault, 17x30x24 concrete', rate: 175, unit: 'each' },
    'HL-UG90':  { desc: 'Install Handhole, 24x36x30 hdpe', rate: 225, unit: 'each' },
    'HL-UG92':  { desc: 'Install Handhole, 17x30x15 hdpe', rate: 175, unit: 'each' },
    'HL-UG98':  { desc: 'Install BDO(SPH14320) Dog house Style Pedestal', rate: 75, unit: 'each' },
    'HL-UG104': { desc: 'Install Handhole, 10" Round JD1000 Flowerpot Style', rate: 65, unit: 'each' },
    'HL-UG110': { desc: 'Install Round Marker Post with locate wire to vault', rate: 15, unit: 'each' },
    'HL-UG118': { desc: 'Dig and swing existing cable and set new 24x36x24 vault', rate: 375, unit: 'each' },
    'HL-UG120': { desc: 'Dig and swing existing cable and set new 17x30x24 vault', rate: 275, unit: 'each' },
    'HL-TREE':  { desc: 'Tree Trimming Labor (includes disposal or stacked)', rate: 1, unit: 'LF' },
    'HL-AE02':  { desc: 'Composite Aerial Placement of Strand', rate: 1, unit: 'LF' },
    'HL-AE06':  { desc: 'Install/lash up to two fiber cables to existing strand', rate: 1.02, unit: 'SF' },
    'HL-AE08':  { desc: 'Install/lash additional (3rd) cable, adder', rate: 0.65, unit: 'SF' },
    'HL-AE10':  { desc: 'Install fiber on strand, rear easement adder', rate: 0.5, unit: 'SF' },
    'HL-AE12':  { desc: 'Overlash fiber on existing cable or aerial Micro duct', rate: 1.3, unit: 'SF' },
    'HL-AE16':  { desc: 'Delash and relash fiber', rate: 1.5, unit: 'SF' },
    'HL-AE18':  { desc: 'Raise/Lower Existing Attachment (simple)', rate: 80, unit: 'each' },
    'HL-AE20':  { desc: 'Raise/Lower Existing attachment (complex)', rate: 110, unit: 'each' },
    'HL-AE34':  { desc: 'Install Riser Guard', rate: 75, unit: 'each' },
    'HL-SPL02': { desc: 'Fiber splicing, Single, includes Power Meter Testing and OTDR', rate: 23, unit: 'each' },
    'HL-SPL08': { desc: 'Fiber splicing labor, other hourly', rate: 150, unit: 'each' },
    'HL-SPL10': { desc: 'Prep and install fiber into splice closure, includes all bonds', rate: 200, unit: 'each' },
    'HL-SPE06': { desc: 'Install place passive splitter cabinet (288 to 576 fiber)', rate: 750, unit: 'each' },
    'HL-SPYJU': { desc: 'Prep and install fiber in FAT Underground, includes all bonds', rate: 200, unit: 'each' },
    'HL-LAB4':  { desc: 'Install concrete pad and place large active cabinet', rate: 4000, unit: 'each' },
    'HL-EM':    { desc: 'Emergency Mobilization (per event)', rate: 500, unit: 'each' },
  },

  HL_GA_MAINT: {
    'HLM1':  { desc: 'Fiber splicing, Single, includes Power Meter Testing and OTDR', rate: 23, unit: 'each' },
    'HLM2':  { desc: 'Prep and install fiber into splice closure, includes all bonds', rate: 200, unit: 'each' },
    'HLM3':  { desc: 'Mid-Sheath (Includes Enclosure Prep)', rate: 250, unit: 'each' },
    'HLM4':  { desc: 'Test (OTDR) Fibers and Provide Traces (Per Fiber)', rate: 10, unit: 'each' },
    'HLM5':  { desc: 'Splicer Hourly Rate for Audits / Troubleshooting', rate: 150, unit: 'each' },
    'HLM6':  { desc: 'Daily Storm Damage Fiber Splicer', rate: 2500, unit: 'each' },
    'HLM7':  { desc: 'Emergency Call Out (Setup Fee)', rate: 500, unit: 'each' },
    'HLM8':  { desc: 'Remove micro fiber from conduit', rate: 0.5, unit: 'LF' },
    'HLM9':  { desc: 'Remove Standard fiber from Conduit', rate: 1, unit: 'LF' },
    'HLM10': { desc: 'Directional Bore up to 2" Conduit', rate: 9, unit: 'LF' },
    'HLM11': { desc: 'Plow 2 1/14" conduits', rate: 3.75, unit: 'LF' },
    'HLM12': { desc: 'Bore, Soft rock adder (with written approval)', rate: 12, unit: 'LF' },
    'HLM13': { desc: 'Bore, Solid rock adder (with written approval)', rate: 35, unit: 'LF' },
    'HLM14': { desc: 'Joint Trench, Place up to two 2" ducts, Min 36"', rate: 1.5, unit: 'LF' },
    'HLM15': { desc: 'Rod and Ream existing conduit', rate: 0.8, unit: 'LF' },
    'HLM16': { desc: 'Set up fee for jobs less than 500\'', rate: 1250, unit: 'each' },
    'HLM17': { desc: 'Set up fee for jobs less than 2000\'', rate: 500, unit: 'each' },
    'HLM18': { desc: 'Pull fiber through conduit', rate: 1, unit: 'LF' },
    'HLM19': { desc: 'Over blow fiber in existing conduit', rate: 1.5, unit: 'LF' },
    'HLM20': { desc: 'Dig and retrieve existing pipe (repair or intercept)', rate: 425, unit: 'each' },
    'HLM22': { desc: 'Place Marker post', rate: 15, unit: 'each' },
    'HLM23': { desc: 'Hand dig trench up to 50\', up to 24"', rate: 16, unit: 'each' },
    'HLM24': { desc: 'Install Vault, 24x36x24 concrete', rate: 225, unit: 'each' },
    'HLM25': { desc: 'Install Vault, 17x30x24 concrete', rate: 175, unit: 'each' },
    'HLM26': { desc: 'Install BDO(SPH14320) Dog house Style Pedestal', rate: 75, unit: 'each' },
    'HLM27': { desc: 'Install Handhole, 10" Round JD1000 Flowerpot Style', rate: 65, unit: 'each' },
    'HLM28': { desc: 'Remove smaller HH and replace with 24x36', rate: 450, unit: 'each' },
    'HLM29': { desc: 'Hourly Supervisor', rate: 85, unit: 'HRS' },
    'HLM30': { desc: 'Hourly Laborer', rate: 35, unit: 'HRS' },
    'HLM31': { desc: 'Hourly Manager', rate: 100, unit: 'HRS' },
    'HLM32': { desc: 'Hourly 2 Man Aerial Crew', rate: 175, unit: 'HRS' },
    'HLM33': { desc: 'Raise/Lower Existing attachment (complex)', rate: 110, unit: 'each' },
    'HLM34': { desc: 'Raise/Lower Existing Attachment (simple)', rate: 80, unit: 'each' },
    'HLM35': { desc: 'Install Riser Guard', rate: 75, unit: 'each' },
    'HLM36': { desc: 'Composite Aerial Placement of Strand', rate: 1, unit: 'LF' },
    'HLM37': { desc: 'Lash Fiber on Strand', rate: 1.02, unit: 'SF' },
    'HLM38': { desc: 'Tree Trimming Labor (includes disposal or stacked)', rate: 1, unit: 'LF' },
    'HLM39': { desc: 'Daily Storm Damage Construction crew', rate: 3500, unit: 'each' },
    'HLM41': { desc: 'Top Pole', rate: 50, unit: 'each' },
    'HLM42': { desc: 'Delash and relash fiber', rate: 1.5, unit: 'SF' },
    'HLM43': { desc: 'Overlash fiber on existing cable or aerial Micro duct', rate: 1.3, unit: 'SF' },
    'HLM48': { desc: 'Mob/Demob (requires pre approval)', rate: 500, unit: 'each' },
    'HLM51': { desc: 'Daily perdium for storm work (per person)', rate: 100, unit: 'each' },
    'HLM54': { desc: 'Install Aerial Drop', rate: 0.52, unit: 'SF' },
  },

  HL_TX: {
    'HL-UG06':  { desc: 'Bore, up to 2" conduit with tracer wire, Min 36" cover', rate: 9, unit: 'LF' },
    'HL-UG08':  { desc: 'Bore, up to 2" conduit with tracer wire, Min 48" cover', rate: 9, unit: 'LF' },
    'HL-UG18':  { desc: 'Bore, pull additional conduit adder up to 2", Min 36"', rate: 1.25, unit: 'LF' },
    'HL-UG26':  { desc: 'Bore, Soft rock adder, Min 36" cover', rate: 14.95, unit: 'LF' },
    'HL-UG28':  { desc: 'Bore, Soft rock adder, Min 48" cover', rate: 14.95, unit: 'LF' },
    'HL-UG30':  { desc: 'Bore, Solid rock adder, Min 36" cover', rate: 69, unit: 'LF' },
    'HL-UG32':  { desc: 'Bore, Solid rock adder, Min 48" cover', rate: 69, unit: 'LF' },
    'HL-UG34':  { desc: 'Plow, Min 36" Depth, one Duct', rate: 3.95, unit: 'LF' },
    'HL-UG36':  { desc: 'Plow, Min 48" Depth, one Duct', rate: 3.95, unit: 'LF' },
    'HL-UG70':  { desc: 'Hand dig trench up to 50\', up to 24"', rate: 500, unit: 'each' },
    'HL-UG72':  { desc: 'Duct rod/locate/rope existing duct', rate: 0.45, unit: 'LF' },
    'HL-UG74':  { desc: 'Place cable in conduit, up to 288 fiber (blow or pull)', rate: 1, unit: 'SF' },
    'HL-UG82':  { desc: 'Install Vault, 24x36x24 concrete', rate: 270, unit: 'each' },
    'HL-UG84':  { desc: 'Install Vault, 17x30x24 concrete', rate: 200, unit: 'each' },
    'HL-UG90':  { desc: 'Install Handhole, 24x36x30 hdpe', rate: 300, unit: 'each' },
    'HL-UG92':  { desc: 'Install Handhole, 17x30x15 hdpe', rate: 200, unit: 'each' },
    'HL-UG98':  { desc: 'Install BDO(SPH14320) Dog house Style Pedestal', rate: 80, unit: 'each' },
    'HL-AE04':  { desc: 'Placement of 1/4" strand and associated pole hardware only', rate: 0.78, unit: 'LF' },
    'HL-AE06':  { desc: 'Install/lash up to two fiber cables to existing strand', rate: 1.15, unit: 'SF' },
    'HL-AE12':  { desc: 'Overlash fiber on existing cable or aerial Micro duct', rate: 1.35, unit: 'SF' },
    'HL-AE16':  { desc: 'Delash and relash fiber', rate: 1.45, unit: 'SF' },
    'HL-AE18':  { desc: 'Raise/Lower Existing Attachment (simple)', rate: 78, unit: 'each' },
    'HL-AE20':  { desc: 'Raise/Lower Existing attachment (complex)', rate: 110, unit: 'each' },
  },

  HL_TX_MAINT: {
    'HLM-UG08':   { desc: 'Bore, up to 4" conduit with tracer wire, Min 48"', rate: 9.5, unit: 'LF' },
    'HLM-UG18':   { desc: 'Bore, pull additional conduit adder up to 2", Min 36"', rate: 1.25, unit: 'LF' },
    'HLM-UG28':   { desc: 'Bore, Soft rock adder (with written approval), Min 48"', rate: 14.95, unit: 'LF' },
    'HLM-UG32':   { desc: 'Bore, Solid rock adder (with written approval), Min 48"', rate: 69, unit: 'LF' },
    'HLM-UG36':   { desc: 'Plow, Min 48" Depth, one Duct, includes 2 pre-rips', rate: 3.75, unit: 'LF' },
    'HLM-UG42':   { desc: 'Plow, Min 48" Depth, 2nd Duct Adder', rate: 1.25, unit: 'LF' },
    'HLM-UG48':   { desc: 'Open Trench, 4" wide chain cut, Min 48"', rate: 9, unit: 'LF' },
    'HLM-UG52':   { desc: 'Open Trench, Mini Excavator, Min 48"', rate: 9, unit: 'LF' },
    'HLM-UG70':   { desc: 'Hand dig trench up to 50\', up to 24"', rate: 500, unit: 'each' },
    'HLM-UG72':   { desc: 'Duct rod/locate/rope existing duct', rate: 0.47, unit: 'LF' },
    'HLM-UG74':   { desc: 'Place cable in conduit, up to 288 fiber (blow or pull)', rate: 1, unit: 'SF' },
    'HLM-UG76':   { desc: 'Place additional cable in conduit, up to 288 fiber, adder', rate: 0.74, unit: 'SF' },
    'HLM-UG78':   { desc: 'Install 144F micro FDH combo pedestal/handhole', rate: 256, unit: 'each' },
    'HLM-UG82':   { desc: 'Install Vault, 24x36x24 concrete', rate: 295, unit: 'each' },
    'HLM-UG84':   { desc: 'Install Vault, 17x30x24 concrete', rate: 225, unit: 'each' },
    'HLM-UG90':   { desc: 'Install Handhole, 24x36x30 hdpe', rate: 325, unit: 'each' },
    'HLM-UG92':   { desc: 'Install Handhole, 17x30x15 hdpe', rate: 280, unit: 'each' },
    'HLM-UG98':   { desc: 'Install BDO(SPH14320) Dog house Style Pedestal', rate: 84, unit: 'each' },
    'HLM-UG102':  { desc: 'Install Handhole, 12x15x12 (flowerpot style)', rate: 47, unit: 'each' },
    'HLM-UG106':  { desc: 'Install Round Marker, hdpe, including bonding', rate: 15, unit: 'each' },
    'HLM-UG110':  { desc: 'Install Round Marker Post with locate wire to vault', rate: 20, unit: 'each' },
    'HLM-UG112':  { desc: 'Install Pedestal, 8" round or square', rate: 30, unit: 'each' },
    'HLM-UG114':  { desc: 'Install Pedestal, 10" round or square', rate: 35, unit: 'each' },
    'HLM-UG116':  { desc: 'Install Pedestal, 12" round or square', rate: 40, unit: 'each' },
    'HLM-UG118':  { desc: 'Dig and swing existing cable and set new 24x36x24 vault', rate: 375, unit: 'each' },
    'HLM-UG120':  { desc: 'Dig and swing existing cable and set new 17x30x24 vault', rate: 300, unit: 'each' },
    'HLM-UG122':  { desc: 'Dig & Swing existing Fiber or Duct', rate: 200, unit: 'each' },
    'HLM-UGM123': { desc: 'Set up fee for jobs less than 500 feet', rate: 1000, unit: 'each' },
    'HL-UGM124':  { desc: 'Set up fee for jobs less than 2000 feet', rate: 500, unit: 'each' },
    'HL-UGM125':  { desc: 'Hourly underground crew', rate: 250, unit: 'per hr' },
    'HL-UGM126':  { desc: 'Emergency call out underground crew', rate: 500, unit: 'each' },
    'HL-UGM127':  { desc: 'Remove Fiber From Conduit', rate: 1, unit: 'SF' },
    'HL-UGM128':  { desc: 'Mob/DeMob', rate: 500, unit: 'each' },
    'HLM-TREE':   { desc: 'Tree Trimming Labor (includes disposal or stacked)', rate: 1.33, unit: 'LF' },
    'HLM-AE06':   { desc: 'Install/lash up to two fiber cables to existing strand', rate: 1.15, unit: 'SF' },
    'HLM-AE12':   { desc: 'Overlash fiber on existing cable or aerial Micro duct', rate: 1.5, unit: 'SF' },
    'HLM-AE16':   { desc: 'Delash and relash fiber', rate: 1.46, unit: 'SF' },
    'HLM-AE18':   { desc: 'Raise/Lower Existing Attachment (simple)', rate: 80, unit: 'each' },
    'HLM-AE20':   { desc: 'Raise/Lower Existing attachment (complex)', rate: 110, unit: 'each' },
    'HLM-AEM43':  { desc: 'Set up fee for jobs less than 500 feet (aerial)', rate: 500, unit: 'each' },
    'HLM-AEM44':  { desc: 'Emergency call out aerial crew', rate: 500, unit: 'each' },
    'HLM-AEM45':  { desc: 'Hourly 3 person aerial crew', rate: 250, unit: 'per hr' },
    'HLM-SPL02':  { desc: 'Fiber splicing, Single, includes Power Meter Testing and OTDR', rate: 27, unit: 'each' },
    'HLM-SPL06':  { desc: 'Fiber testing/OTDR trace per strand', rate: 10, unit: 'each' },
    'HLM-SPL07':  { desc: 'Add fiber to existing enclosure', rate: 150, unit: 'each' },
    'HLM-SPL08':  { desc: 'Fiber splicing labor, other hourly', rate: 150, unit: 'per hour' },
    'HLM-SPL10':  { desc: 'Prep and install fiber into splice closure, includes all bonds', rate: 200, unit: 'each' },
    'HLM-SPYJU':  { desc: 'Prep and install fiber in FAT Underground, includes all bonds', rate: 200, unit: 'each' },
    'HLM-SPYJA':  { desc: 'Prep and install fiber in FAT Aerial, includes all bonds', rate: 250, unit: 'each' },
    'HLM-SPE02':  { desc: 'Prep and install fiber into pedestal (up to 12x12)', rate: 185, unit: 'each' },
    'HLM-SPE06':  { desc: 'Install place passive splitter cabinet (288 to 576 fiber)', rate: 950, unit: 'each' },POINT_BB: {
    'PB06':   { desc: 'Composite Aerial Placement of Strand', rate: 0.85, unit: 'LF' },
    'PB32':   { desc: 'Lash 1st Mainline Fiber Cable', rate: 1, unit: 'SF' },
    'PB39':   { desc: 'Overlash', rate: 1.45, unit: 'SF' },
    'PB41':   { desc: 'Delash - Relash Fiber', rate: 1.5, unit: 'SF' },
    'PB03':   { desc: 'Lash Additional Mainline Cable w/ 1st Cable in same bundle', rate: 0.5, unit: 'SF' },
    'PB61':   { desc: 'Place 12 ct Flat Drop', rate: 0.7, unit: 'SF' },
    'PB33':   { desc: 'Tree trimming per span with pre approval', rate: 100, unit: 'each' },
    'PB54':   { desc: 'Pole Transfer Simple', rate: 120, unit: 'each' },
    'PB55':   { desc: 'Pole Transfer Complex', rate: 150, unit: 'each' },
    'PB27':   { desc: 'Raise/Lower Existing Attachment Simple', rate: 80, unit: 'each' },
    'PB28':   { desc: 'Raise/Lower Existing Attachment Complex', rate: 110, unit: 'each' },
    'PB71':   { desc: 'Aerial Wreck Out', rate: 0.3, unit: 'LF' },
    'PB05':   { desc: 'Install Riser Guard', rate: 75, unit: 'each' },
    'PB07':   { desc: 'Composite Underground Conduit Placement - up to 2"', rate: 8.75, unit: 'LF' },
    'PB40':   { desc: 'Plow single conduit', rate: 5, unit: 'LF' },
    'PB58':   { desc: 'Trench Single Conduit', rate: 4.5, unit: 'LF' },
    'PB38':   { desc: 'Hand dig trench up to 50\'', rate: 15, unit: 'LF' },
    'PB08':   { desc: 'Cut and Restore Asphalt or Concrete', rate: 27, unit: 'SF' },
    'PB09':   { desc: 'Conduit Adder in same trench - up to 2"', rate: 2.75, unit: 'LF' },
    'PB24':   { desc: 'Blow / Pull fiber through conduit', rate: 1, unit: 'SF' },
    'PB12':   { desc: 'Keyhole Saw for Microtrench and install fiber key', rate: 275, unit: 'each' },
    'PB13':   { desc: 'Install Coyote GLC Pedestal (16x16)', rate: 100, unit: 'each' },
    'PB14':   { desc: 'Install Vault (17x30x24)', rate: 225, unit: 'each' },
    'PB15':   { desc: 'Install Vault (24x36x24)', rate: 275, unit: 'each' },
    'PB42':   { desc: 'Dig and retrieve and set (17x30x24)', rate: 275, unit: 'each' },
    'PB43':   { desc: 'Dig and retrieve and set (24x36x24)', rate: 325, unit: 'each' },
    'PB37':   { desc: 'Install handhole 12x15x12', rate: 80, unit: 'each' },
    'PB17':   { desc: 'Install Cable Marker', rate: 10, unit: 'each' },
    'PB36':   { desc: 'Splice Closure Preparation', rate: 200, unit: 'each' },
    'PB35':   { desc: 'Single Fusion Fiber Splicing includes bidirectional OTDR', rate: 20, unit: 'each' },
    'PB56':   { desc: 'Wall Mount Enclosure', rate: 120, unit: 'each' },
    'PB62':   { desc: 'Electrical wiring for cabinet', rate: 500, unit: 'each' },
    'PB63':   { desc: 'Construct H Frame', rate: 500, unit: 'each' },
    'PB65':   { desc: 'Pull Power Wire', rate: 1, unit: 'LF' },
    'PB68':   { desc: 'Mount Meter and Disconnect on Pole', rate: 350, unit: 'each' },
    'PB25':   { desc: 'Install Cabinet', rate: 3800, unit: 'each' },
    'PBM101': { desc: 'Fusion Splice Cost Per Fiber, 1-24', rate: 24, unit: 'each' },
    'PBM102': { desc: 'Fusion Splice Cost Per Fiber, 25-96', rate: 21, unit: 'each' },
    'PBM103': { desc: 'Fusion Splice Cost per Fiber, > 96', rate: 16.5, unit: 'each' },
    'PBM104': { desc: 'Prep cables into new closure', rate: 200, unit: 'each' },
    'PBM105': { desc: 'Re-entry (Enclosure)', rate: 100, unit: 'each' },
    'PBM106': { desc: 'Mid-Sheath (Includes Enclosure Prep)', rate: 250, unit: 'each' },
    'PBM107': { desc: 'Add new cable(s) to existing closure', rate: 165, unit: 'each' },
    'PBM108': { desc: 'Backboard Installation', rate: 150, unit: 'each' },
    'PBM109': { desc: 'Test (OTDR) Fibers and Provide Traces (Per Fiber)', rate: 10, unit: 'each' },
    'PBM110': { desc: 'Emergency Call Out (Setup Fee)', rate: 500, unit: 'each' },
    'PBM111': { desc: 'Hourly Rate for Audits / Troubleshooting', rate: 125, unit: 'each' },
    'PBM112': { desc: 'Mobilization Fee (When Released 1 Job 2.5+ Hours Away)', rate: 200, unit: 'each' },
    'PBM114': { desc: 'Remove micro fiber from conduit', rate: 0.5, unit: 'LF' },
    'PBM115': { desc: 'Remove Standard fiber', rate: 1, unit: 'LF' },
    'PBM116': { desc: 'Cable Bonding', rate: 25, unit: 'each' },
    'PBM117': { desc: 'Lower and rehang aerial enclosure', rate: 350, unit: 'each' },
    'PBM119': { desc: 'Directional Bore up to 2" Conduit', rate: 9, unit: 'LF' },
    'PBM120': { desc: 'Directional Bore Metro', rate: 15, unit: 'LF' },
    'PBM123': { desc: 'Set up fee for jobs less than 500\'', rate: 1250, unit: 'each' },
    'PBM124': { desc: 'Set up fee for jobs less than 2000\'', rate: 500, unit: 'each' },
    'PBM125': { desc: 'Pull fiber through conduit', rate: 1, unit: 'LF' },
    'PBM126': { desc: 'Over blow fiber in existing conduit', rate: 1.5, unit: 'LF' },
    'PBM127': { desc: 'Soft Rock Bore adder', rate: 14, unit: 'LF' },
    'PBM128': { desc: 'Solid Rock Bore adder', rate: 69, unit: 'LF' },
    'PBM129': { desc: 'Place Handhole (36"x24"x36") and ground rod', rate: 300, unit: 'each' },
    'PBM133': { desc: 'Place Marker post', rate: 15, unit: 'each' },
    'PBM135': { desc: 'Dig and retrieve existing pipe (repair or intercept)', rate: 425, unit: 'each' },
    'PBM136': { desc: 'Remove smaller HH and replace with 24x36', rate: 450, unit: 'each' },
    'PBM137': { desc: 'Concrete/Asphalt remove and replace per sq ft', rate: 30, unit: 'SQFT' },
    'PBM138': { desc: 'Place 1/4" strand and Hardware', rate: 1.75, unit: 'LF' },
    'PBM139': { desc: 'Place screw anchor, down guy, and guy guard', rate: 39, unit: 'each' },
    'PBM140': { desc: 'Build Riser', rate: 65, unit: 'each' },
    'PBM141': { desc: 'Lash fiber on bare strand', rate: 1.5, unit: 'SF' },
    'PBM142': { desc: 'Overlash Fiber', rate: 2, unit: 'SF' },
    'PBM145': { desc: 'Set pole by hand', rate: 710, unit: 'each' },
    'PBM146': { desc: 'Set Pole with Truck', rate: 540, unit: 'each' },
    'PBM151': { desc: 'Additional 1.25" inch HDPE PIPE', rate: 3, unit: 'LF' },
    'PBM152': { desc: 'Hourly Supervisor', rate: 85, unit: 'HRS' },
    'PBM153': { desc: 'Hourly Laborer', rate: 35, unit: 'HRS' },
    'PBM154': { desc: 'Hourly Manager', rate: 100, unit: 'HRS' },
    'PBM155': { desc: 'Hourly 2 Man Aerial Crew', rate: 175, unit: 'HRS' },
    'PBM156': { desc: 'Ground Rod Placement', rate: 10, unit: 'each' },
    'PBM157': { desc: 'Place NEMA Cabinet', rate: 400, unit: 'each' },
    'PBM158': { desc: 'Core Drill Concrete or Asphalt', rate: 300, unit: 'each' },
    'PBM160': { desc: 'MPO and LGX placement', rate: 150, unit: 'each' },
    'PBM161': { desc: 'Rod and Rope existing conduit', rate: 0.55, unit: 'LF' },
    'PBM162': { desc: 'Install PVC or EMT conduit interior', rate: 5, unit: 'LF' },
    'PBM163': { desc: 'Install PVC or EMT conduit exterior', rate: 4.5, unit: 'LF' },
    'PBM164': { desc: 'Mob/Demob', rate: 500, unit: 'each' },
    'PBM168': { desc: 'Daily Storm Damage Construction crew', rate: 3500, unit: 'each' },
    'PBM169': { desc: 'Daily perdium for storm work (per person)', rate: 100, unit: 'each' },
    'PBM170': { desc: 'Daily Storm Damage Fiber Splicer', rate: 2500, unit: 'each' },
    'PBM171': { desc: 'Decom', rate: 1700, unit: 'each' },
    'PBM172': { desc: 'Decom and remove cabinet', rate: 2500, unit: 'each' },
    'PBM173': { desc: 'Decom and remove cabinet and reroute pipe', rate: 3000, unit: 'each' },
    'PBM174': { desc: 'Decom trip charge', rate: 225, unit: 'each' },
    'PBM175': { desc: 'Hourly Underground Crew', rate: 175, unit: 'HRS' },
    'PBM176': { desc: 'Resag Strand', rate: 0.8, unit: 'LF' },
    'PBM177': { desc: 'Remove Existing Cabinet and Demo Pad', rate: 1950, unit: 'each' },
    'PBM178': { desc: 'Equipment Maintenance', rate: 2500, unit: 'each' },
    'PBM179': { desc: 'Daily Aerial Crew', rate: 3500, unit: 'each' },
  },

  AFN: {
    'AFN01':  { desc: 'TDC Only - Testing Day Rate up to 3 Splicers', rate: 4250, unit: 'EA' },
    'AFN01A': { desc: 'Testing Day Rate up to 3 Splicers', rate: 4250, unit: 'EA' },
    'AFN03':  { desc: 'Fusion Splice', rate: 27, unit: 'EA' },
    'AFN04':  { desc: 'Add New Cable to Existing Splice Enclosure (Per Cable)', rate: 165, unit: 'EA' },
    'AFN05':  { desc: 'Test Fiber - Provide OTDR Shots', rate: 10, unit: 'EA' },
    'AFN06':  { desc: 'Directional Bore (Less than 200\')', rate: 12, unit: 'LF' },
    'AFN07':  { desc: 'Place 24x36x24 Handhole', rate: 400, unit: 'EA' },
    'AFN08':  { desc: 'Set up fee for job less than 500\'', rate: 1250, unit: 'EA' },
    'AFN09':  { desc: 'Pull Fiber Through Conduit', rate: 1, unit: 'LF' },
    'AFN11':  { desc: 'Enclosure Prep', rate: 200, unit: 'EA' },
    'AFN12':  { desc: 'Ground Rod Placement', rate: 25, unit: 'EA' },
    'AFN14':  { desc: 'Misc Engineering', rate: 500, unit: 'EA' },
    'AFN15':  { desc: 'Wall Mount Fiber Distribution Panel', rate: 150, unit: 'EA' },
    'AFN17':  { desc: 'Set up fee for job less than 2000\'', rate: 500, unit: 'EA' },
    'AFN18':  { desc: 'Mobilization Fee (When Released 1 Job 2.5+ Hours Away)', rate: 300, unit: 'EA' },
    'AFN19':  { desc: 'Mid-Sheath (Includes Enclosure Prep)', rate: 250, unit: 'EA' },
    'AFN20':  { desc: 'Access Existing Conduit Standard', rate: 350, unit: 'EA' },
    'AFN21':  { desc: 'Directional Drill and install single 1.5" OR 2.0" HDPE Conduit', rate: 9, unit: 'LF' },
  },

  LIGHTSPEED: {
    'LS01': { desc: 'Composite UG Conduit Placement - up to 1.25" conduit', rate: 14.5, unit: 'LF' },
    'LS02': { desc: 'Rock Adder - Requires Pictures', rate: 15, unit: 'LF' },
  },

  DEJA_BLUE: {
    'DB01': { desc: 'Install (1) 1.25 Conduit', rate: 13, unit: 'LF' },
    'DB02': { desc: 'Install (1) 0.5 Microduct', rate: 13, unit: 'LF' },
  },

  BEARDED_TURKEY: {
    'BT01': { desc: 'Install (1) 1.25 Conduit', rate: 13, unit: 'LF' },
    'BT02': { desc: 'Install (1) 0.5 Microduct', rate: 13, unit: 'LF' },
  },

  NEW_ERA: {
    'NE01': { desc: 'Install (1) 1.25 Conduit', rate: 13, unit: 'LF' },
    'NE02': { desc: 'Install (1) 0.5 Microduct', rate: 13, unit: 'LF' },
  },

  UNITED_TELEPORTS: {
    'UT01': { desc: 'Directional Bore 4" SRD 13.5', rate: 27, unit: 'LF' },
    'UT02': { desc: 'Place 24x36x36 Handhole', rate: 400, unit: 'each' },
  },

};

function lookupRate(code, customerKey) {
  const upper = code.trim().toUpperCase();
  if (customerKey && RATE_CARDS[customerKey]) {
    return RATE_CARDS[customerKey][upper] || RATE_CARDS[customerKey][code.trim()] || null;
  }
  for (const card of Object.values(RATE_CARDS)) {
    if (card[upper]) return card[upper];
    if (card[code.trim()]) return card[code.trim()];
  }
  return null;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { RATE_CARDS, lookupRate };
} else {
  window.RATE_CARDS = RATE_CARDS;
  window.lookupRate = lookupRate;
}
    'HLM-SPEM07': { desc: 'Emergency call out fiber splicer', rate: 500, unit: 'each' },
    'HLM-LAB2':   { desc: 'Install Ground Rod with wire and clamp', rate: 30, unit: 'each' },
    'HLM-LAB4':   { desc: 'Install concrete pad and place large active cabinet', rate: 2100, unit: 'each' },
    'HLM-LAB6':   { desc: 'Install concrete pad and place small/mini active cabinet', rate: 1300, unit: 'each' },
    'HLM-LAB8':   { desc: 'Install concrete pad and place passive splitter cabinet', rate: 1100, unit: 'each' },
    'HLM-LAB10':  { desc: 'Install H-frame for mini OLT', rate: 325, unit: 'each' },
    'HLM-LAB12':  { desc: 'Core Drill Building up to 4" Diameter', rate: 275, unit: 'each' },
    'HLM-HS02':   { desc: 'Cut, Remove & Replace Concrete', rate: 25, unit: 'SQFT' },
    'HLM-HS04':   { desc: 'Cut, Remove & Replace Asphalt', rate: 28, unit: 'SQFT' },
    'HL-SPL02':   { desc: 'Fiber splicing, Single, includes Power Meter Testing and OTDR', rate: 27, unit: 'each' },
    'HL-SPL10':   { desc: 'Prep and install fiber into splice closure, includes all bonds', rate: 200, unit: 'each' },
  },
    'UNSP10': { desc: 'UNSP10-Add new cable(s) to existing closure', rate: 165, unit: 'EA' },
    'UNSP11': { desc: 'UNSP11-Install FDP Panel', rate: 75, unit: 'EA' },
    'UNSP12': { desc: 'UNSP12-Backboard Installation', rate: 150, unit: 'EA' },
    'UNSP13': { desc: 'UNSP13-Test (OTDR) Fibers and Provide Traces (Per Fiber)', rate: 10, unit: 'EA' },
    'UNSP14': { desc: 'UNSP14-Emergency Call Out (Setup Fee)', rate: 500, unit: 'EA' },
    'UNSP15': { desc: 'UNSP15-Hourly Rate for Audits', rate: 100, unit: 'HRS' },
    'UNSP16': { desc: 'UNSP16-Mobilization Fee (When Released 1 Job 2.5+ Hours Away)', rate: 200, unit: 'EA' },
    'UNSP17': { desc: 'UNSP17-Remove fiber from conduit', rate: 1, unit: 'LF' },
    'UNSP18': { desc: 'UNSP18-Cable Bonding', rate: 25, unit: 'EA' },
  },
